mySQLConfig: &mySqlConfig
    code: mysql
    driverName: mysql
    urlAddress: "root:@tcp(localhost:4333)/service_config?charset=utf8"
    dbName:
couchdbConfig: &couchdbConfig
    code: couch
    driverName: couch
    urlAddress: http://admin:admin@localhost:5984
    dbName: animals
cacheGrpcConfig: &cacheGrpcConfig
    code: cacheGrpc
    driverName: cache
    urlAddress: localhost:5051
zapConfig: &zapConfig
    code: zap
    level: debug
    enableCaller: true
logrusConfig: &logrusConfig
    code: logrus
    level: debug
    enableCaller: false
logConfig: *zapConfig
useCaseConfig:
    registration:
        code: registration
        userDataConfig: &userDataConfig
            code: userData
            dataStoreConfig: *mySqlConfig
        txDataConfig: &txDataConfig
            code: txData
            dataStoreConfig: *mySqlConfig
    listUser:
        code: listUser
        userDataConfig: *userDataConfig
        cacheDataConfig: &cacheDataConfig
            code: cacheData
            dataStoreConfig: *cacheGrpcConfig
